add_newline = true

[git_branch]
#symbol = ' '
format = 'on [$symbol$branch]($style)'
# truncation_length = 4
truncation_symbol = '…/'
style = 'bold blue'

# Shows current git status
[git_status]
format = ' [$all_status$ahead_behind]($style) '
style = 'bold green'
conflicted = ' '
up_to_date = '󱫐 '
untracked = '  '
ahead = ' ⇡${count}'
behind = ' ⇣${count}'
diverged = ' ⇕⇡${ahead_count}⇣${behind_count}'
stashed = '  '
modified = '  '
staged = '[++\($count\)](green)'
renamed = ' 󰑕 '
deleted = '  '

[python]
symbol = ' '

[rust]
symbol = ' '

[package]
symbol = ' '

[c]
symbol = ' '

[elixir]
symbol = ''
